### PR TITLE
Es6 remastered: Added PropTypes

### PR DESCRIPTION
**Pull request by bjlaa**

### CODE REVIEW

**Comment by FredericoAndrade** [comment]
image

@bjlaa Book language flip is broken. Also, it would be good to merge master into this branch before closing this branch to resolve all the conflicts here.

image

**Comment by bjlaa** [comment]
@FredericoAndrade  There was a missing method binding. I thoroughly went through all the other components to see if I had forgot any other and everything now works properly. 
I'll have a look on the merging in the weekend.

**Comment by FredericoAndrade** [comment]
@bjlaa hows the conflict fixing coming?

**Comment by bjlaa** [comment]
@FredericoAndrade Just merged the last updates from master. The branch is up-to-date and ready to be merged.

**Comment by FredericoAndrade** [comment]
Hey @bjlaa, it seems like there are still some merges that need fixing. Would you like to take care of them or shall I?
image

**Comment by bjlaa** [comment]
Seems that I forgot to sync in Github Desktop after merging in master; it is now done.

**Pull request merged**
